# Generated by Django 4.1.7 on 2023-08-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployee',
            name='department',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Commercial'), (2, 'Support'), (3, 'Gestion')], default=3),
        ),
    ]
